name: Generate & Publish API Client

on:
  workflow_dispatch: # <-- optional, nur manuell startbar

jobs:
  generate-client:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout dieses Repo (open-api-code-gen)
      - name: Checkout api-clients repo
        uses: actions/checkout@v3
        with:
          repository: bonbonn1912/open-api-code-gen

      # 2. Checkout das Projekt, aus dem die OpenAPI-Spec kommt
      #    (hier als Beispiel Project A, du kannst es anpassen)
      - name: Checkout Project A
        uses: actions/checkout@v3
        with:
          repository: bonbonn1912/tuya-service

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generate & Publish Client
        run: |
          ./gradlew publish \
            -PclientName=tuya \
            -PinputSpec=../tuya-service/src/main/resources/openapi.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}